### ISSUE TITLE
empty containedVertices for all nodes

### ISSUE THREAD

**Issue by bzfhille** [VieCut/VieCut#7]
When testing with a simple graph [test_cactus.txt](https://github.com/VieCut/VieCut/files/10483374/test_cactus.txt) (this is actually a K_4), I see that all `containedVertices` are empty:
```
build (print-contained-vertices)] ./mincut test_cactus.txt cactus 
io time: 0.000262976
0: 
1: 
2: 
3: 
4: 
RESULT algo=cactusdefault graph=test_cactus.txt time=0.000452042 cut=3 n=4 m=6 processes=1 edge_select=heavy_vertex seed=0
```
For reference, I pushed the modified branch I used to print in my forked repo: https://github.com/bzfhille/VieCut/tree/print-contained-vertices
Maybe I added the printing at the wrong place.

**Comment by alexnoe** [comment]
(Sorry for the delay again)

The graph file looks good to me, I don't think the problem is there.

I currently do not have a UNIX machine available to me, so I am unable to run the code, but looking at this test https://github.com/bzfhille/VieCut/blob/master/tests/cactus_cut_test.cpp#L389 you should add CLI parameter -s (to enable save_cut and actually maintain the vertices on either side of the minimum cut(s)) [https://github.com/bzfhille/VieCut/blob/master/app/mincut.cpp#L58] - this seems to be the only difference between the tests and your example code.

**Comment by bzfhille** [comment]
Thanks, this change fixes the issue. I adjusted my code to export the GraphML file to implicitly enable `-s`, too.
